# Generated by Django 4.2.6 on 2023-10-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
                ('league', models.CharField(max_length=255)),
                ('club', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('stats_id', models.AutoField(primary_key=True, serialize=False)),
                ('matches_played', models.IntegerField()),
                ('substitution', models.IntegerField()),
                ('mins', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('xG', models.FloatField()),
                ('xG_per_avg_match', models.FloatField()),
                ('shots', models.IntegerField()),
                ('on_target', models.IntegerField()),
                ('shots_per_avg_match', models.FloatField()),
                ('on_target_per_avg_match', models.FloatField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
