# Generated by Django 4.2.6 on 2023-11-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TopScorers', '0004_player_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TopScorers.stats', default='Domyślna Wartość'),
        ),
    ]
