# Generated by Django 4.2.6 on 2023-11-24 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TopScorers', '0005_player_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club',
            new_name='club_name',
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TopScorers.club'),
        ),
    ]
